ci/android: fix Android SDK installation
Google dropped the deprecated `tools` package from the SDK repository index;
android-actions/setup-android (as of v3 or v4) still rely on it, which leads to
the following error:

  Warning: Failed to find package 'tools'
  Error: The process '.../sdkmanager' failed with exit code 1

Run setup-android with platform-tools instead.